
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package  com.xml.poverenik.ws.izvestaj;

import java.util.logging.Logger;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.xml.poverenik.service.IzvestajService;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2021-02-04T19:44:58.797+01:00
 * Generated source version: 3.2.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "ReportService",
                      portName = "ReportServiceSoapBinding",
                      targetNamespace = "http://izvestaj",
                      wsdlLocation = "src/main/resources/wsdl/izvestaj.wsdl",
                      endpointInterface = "com.xml.poverenik.ws.izvestaj.ReportServicePortType")
@Service         
public class ReportServiceSoapBindingImpl implements ReportServicePortType {

	@Autowired
	private IzvestajService service;
    private static final Logger LOG = Logger.getLogger(ReportServiceSoapBindingImpl.class.getName());

    /* (non-Javadoc)
     * @see izvestaj.ReportServicePortType#sendReport(message.Message message)*
     */
    public void sendReport( com.xml.poverenik.ws.izvestaj.Message message) { 
        LOG.info("Executing operation sendReport");
        System.out.println(message);
        try {
        	service.makeIzvestaj(message);    	        	
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
