
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.xml.projekat.ws.resenje;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.xml.projekat.service.ResenjeService;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2021-02-05T11:36:55.102+01:00
 * Generated source version: 3.2.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "DecisionService",
                      portName = "DecisionServiceSoapBinding",
                      targetNamespace = "http://resenje",
                      wsdlLocation = "src/main/resources/wsdl/resenje.wsdl",
                      endpointInterface = "com.xml.projekat.ws.resenje.DecisionServicePortType")
@Service
public class DecisionServiceSoapBindingImpl implements DecisionServicePortType {

	@Autowired
	public ResenjeService service;
	
    private static final Logger LOG = Logger.getLogger(DecisionServiceSoapBindingImpl.class.getName());

    /* (non-Javadoc)
     * @see resenje.DecisionServicePortType#sendDecision(dokument_resenje.DokumentResenje dokumentResenje)*
     */
    public void sendDecision(com.xml.projekat.ws.resenje.DokumentResenje dokumentResenje) { 
        LOG.info("Executing operation sendDecision");
        System.out.println(dokumentResenje);
        System.out.println("Aassssssssssssssssssssssssssssssssssssssssssssssss");
        try {
        	service.createResenje(dokumentResenje);  
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
