package com.xml.projekat.ws.resenje;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2021-02-05T11:36:55.186+01:00
 * Generated source version: 3.2.0
 * 
 */
@WebServiceClient(name = "DecisionService", 
                  wsdlLocation = "src/main/resources/wsdl/resenje.wsdl",
                  targetNamespace = "http://resenje") 
public class DecisionService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://resenje", "DecisionService");
    public final static QName DecisionServiceSoapBinding = new QName("http://resenje", "DecisionServiceSoapBinding");
    static {
        URL url = DecisionService.class.getClassLoader().getResource("wsdl/resenje.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(DecisionService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "src/main/resources/wsdl/resenje.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public DecisionService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DecisionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DecisionService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public DecisionService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DecisionService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DecisionService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns DecisionServicePortType
     */
    @WebEndpoint(name = "DecisionServiceSoapBinding")
    public DecisionServicePortType getDecisionServiceSoapBinding() {
        return super.getPort(DecisionServiceSoapBinding, DecisionServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DecisionServicePortType
     */
    @WebEndpoint(name = "DecisionServiceSoapBinding")
    public DecisionServicePortType getDecisionServiceSoapBinding(WebServiceFeature... features) {
        return super.getPort(DecisionServiceSoapBinding, DecisionServicePortType.class, features);
    }

}
