package com.xml.projekat.ws.hello;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2021-02-03T14:43:15.551+01:00
 * Generated source version: 3.2.0
 * 
 */
@WebServiceClient(name = "HelloDocumentService", 
                  wsdlLocation = "classpath:wsdl/HelloDocument.wsdl",
                  targetNamespace = "http://projekat.xml.com/ws/hello") 
public class HelloDocumentService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://projekat.xml.com/ws/hello", "HelloDocumentService");
    public final static QName HelloDocumentPort = new QName("http://projekat.xml.com/ws/hello", "HelloDocumentPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Milica/Desktop/XML-i-veb-servisi/dokumenti/projekat/src/main/resources/wsdl/HelloDocument.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloDocumentService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Predator/Desktop/XML/SOAP%20JAX-WS%20(Example%203)/src/main/resources/wsdl/HelloDocument.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloDocumentService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloDocumentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloDocumentService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public HelloDocumentService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HelloDocumentService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HelloDocumentService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns HelloDocument
     */
    @WebEndpoint(name = "HelloDocumentPort")
    public HelloDocument getHelloDocumentPort() {
        return super.getPort(HelloDocumentPort, HelloDocument.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloDocument
     */
    @WebEndpoint(name = "HelloDocumentPort")
    public HelloDocument getHelloDocumentPort(WebServiceFeature... features) {
        return super.getPort(HelloDocumentPort, HelloDocument.class, features);
    }

}
