
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.xml.projekat.ws.hello;

import java.util.logging.Logger;

import javax.xml.bind.JAXBElement;

import com.xml.projekat.ws.hello.types.ObjectFactory;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2021-02-03T14:43:15.486+01:00
 * Generated source version: 3.2.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "HelloDocumentService",
                      portName = "HelloDocumentPort",
                      targetNamespace = "http://projekat.xml.com/ws/hello",
                      wsdlLocation = "classpath:wsdl/HelloDocument.wsdl",
                      endpointInterface = "com.xml.projekat.ws.hello.HelloDocument")
                      
public class HelloDocumentImpl implements HelloDocument {

    private static final Logger LOG = Logger.getLogger(HelloDocumentImpl.class.getName());

    public java.lang.String sayHelloMiss(com.xml.projekat.ws.hello.types.RequestMissType requestMiss) { 
    	LOG.info("Executing operation sayHelloMiss");
		System.out.println(requestMiss);
		
		ObjectFactory helloFactory = new ObjectFactory();
		JAXBElement<String> response = helloFactory.createResponseMiss("Hello miss" + requestMiss.getFirstName() + " " + requestMiss.getLastName());
		return response.getValue();
    }

}
