package com.xml.email.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.xml.email.data.types.Message;
import com.xml.email.data.types.ObjectFactory;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-03T23:27:36.997+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://mail", name = "EmailServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.DOCUMENT)
public interface EmailServicePortType {

    @WebMethod(action = "http://email/ws/posaljiPoruku")
    public void posaljiPoruku(
        @WebParam(partName = "message", name = "message")
        Message message
    );
}
