
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.xml.email.soap;

import java.util.logging.Logger;

import javax.mail.internet.MimeMessage;
import javax.mail.util.ByteArrayDataSource;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.env.Environment;
import org.springframework.mail.javamail.JavaMailSenderImpl;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

import com.xml.email.data.types.Message;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-03T23:27:36.845+01:00
 * Generated source version: 3.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "EmailService",
                      portName = "EmailServiceSoapBinding",
                      targetNamespace = "http://mail",
                      wsdlLocation = "src/main/resources/data/mail.wsdl",
                      endpointInterface = "com.xml.email.soap.EmailServicePortType")
@Service                    
public class EmailServiceSoapBindingImpl implements EmailServicePortType {

    private static final Logger LOG = Logger.getLogger(EmailServiceSoapBindingImpl.class.getName());

    @Autowired
    JavaMailSenderImpl mailSender;
    
    @Autowired
    Environment env;
    
    /* (non-Javadoc)
     * @see mail.EmailServicePortType#posaljiPoruku(message.Message message)*
     */
    public void posaljiPoruku(Message message) { 
        LOG.info("Executing operation posaljiPoruku");
        System.out.println(message);
        try {
        	mailSender.setUsername(env.getProperty("spring.mail.username"));
    		mailSender.setPassword(env.getProperty("spring.mail.password"));
    		
    		MimeMessage mimeMessage = mailSender.createMimeMessage();
            MimeMessageHelper email = new MimeMessageHelper(mimeMessage, true, "utf-8");
            
            email.setTo(message.getPrimalac());
            email.setSubject(message.getNaslov());
            email.setText(message.getSadrzaj());
            
            if(message.getTipPriloga().equals("pdf")) {
           	 ByteArrayDataSource dataSource = new ByteArrayDataSource(message.getPrilog(), "application/pdf");
                email.addAttachment("attachment."+message.getTipPriloga(), dataSource);
           }else if (message.getTipPriloga().equals("html")) {
           	ByteArrayDataSource dataSource = new ByteArrayDataSource(message.getPrilog(), "text/html");
               email.addAttachment("attachment."+message.getTipPriloga(), dataSource);
   		}
          
           mailSender.send(mimeMessage);
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
